SERVER = 'postgres'
SQL_FLAVOUR = 'postgresql'
DRIVER = 'psycopg2'
USER = 'postgres'
PASSWORD = 'pwd'
HOSTNAME = 'localhost'
DATABASE = '123'
CONNECTION_STRING = f'{SQL_FLAVOUR}+{DRIVER}://{USER}:{PASSWORD}@{HOSTNAME}/{DATABASE}'
